# Generated by Django 5.1.4 on 2025-01-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('repeated_password', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
